### ISSUE TITLE
iOS无法运行项目

### ISSUE THREAD

**Issue by Matcha-xiaobin** [Lavmee/precompose-navigation-typesafe#6]
> Task :composeApp:compileKotlinIosX64 FAILED
/Users/chen/IdeaProjects/KotlinProject/composeApp/src/commonMain/kotlin/ui/MainContent.kt:297:37: error: Argument type mismatch: actual type is 'kotlin.Any', but 'kotlin.String' was expected.

![image](https://github.com/Lavmee/precompose-navigation-typesafe/assets/5775066/f248c300-d15c-4d5f-a7f2-a14adbddb25d)
![image](https://github.com/Lavmee/precompose-navigation-typesafe/assets/5775066/89771d44-bcf8-4927-b794-d5274db91872)
![image](https://github.com/Lavmee/precompose-navigation-typesafe/assets/5775066/76fac6d8-6ddd-4d91-9946-d664a6c19aa4)

以上是我的代码部分，ios一直无法成功编译。

**Comment by Matcha-xiaobin** [comment]
android 和desktop 正常使用。

**Comment by Matcha-xiaobin** [comment]
![image](https://github.com/Lavmee/precompose-navigation-typesafe/assets/5775066/95620d15-6e11-4d08-8170-ed510f04c2ac)
目前发现采用这种方式后，问题得到解决。不清楚什么原因导致的。

**Comment by Lavmee** [comment]
I tried to reproduce the error on iOS, but everything seems to work fine.

```kotlin
// Based on sample
@Composable
internal fun AppNavigation() {
    val navigator = rememberNavigator()
    val navItems = remember { listOf(AppRoutes.Home, AppRoutes.Group) }
    Scaffold(
        bottomBar = {
            NavigationBar {
                navItems.forEachIndexed { index, route ->
                    NavigationBarItem(
                        selected = false,
                        label = { Text("Route $index") },
                        icon = { Icon(imageVector = Icons.Default.Home, contentDescription = null) },
                        onClick = { navigator.navigate(route, NavOptions(launchSingleTop = true)) }
                    )
                }
            }
        }
    ) { innerPadding ->
        //NavHost here
    }
}
```
